import { StyleSheet } from "react-native";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  scrollContainer: {
    paddingBottom: hp("5%"),
    paddingTop: hp("3%"),
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: wp("5%"),
    paddingTop: hp("5%"),
    paddingBottom: hp("2%"),
  },
  backButton: {
    padding: wp("2%"),
  },
  headerTitle: {
    fontSize: wp("6%"),
    fontWeight: "bold",
    color: "#420F54",
    marginLeft: wp("3%"),
    fontFamily: "Poppins-Bold",
  },
  pageTitle: {
    fontSize: wp("6%"),
    fontWeight: "bold",
    color: "#420F54",
    marginBottom: hp("2%"),
    fontFamily: "Poppins-Bold",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    marginTop: hp("2%"),
    fontSize: wp("4%"),
    color: "#420F54",
    fontFamily: "Poppins-Regular",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: wp("5%"),
  },
  errorTitle: {
    fontSize: wp("5%"),
    fontWeight: "bold",
    color: "#D32F2F",
    marginTop: hp("2%"),
    marginBottom: hp("1%"),
    fontFamily: "Poppins-Bold",
  },
  errorMessage: {
    fontSize: wp("4%"),
    color: "#666",
    textAlign: "center",
    marginBottom: hp("3%"),
    fontFamily: "Poppins-Regular",
  },
  retryButton: {
    backgroundColor: "#420F54",
    paddingVertical: hp("1%"),
    paddingHorizontal: wp("5%"),
    borderRadius: wp("3%"),
    marginBottom: hp("2%"),
  },
  retryButtonText: {
    color: "#fff",
    fontSize: wp("4%"),
    fontWeight: "bold",
    fontFamily: "Poppins-Bold",
  },
  summaryContainer: {
    backgroundColor: "#F3E4FF",
    borderRadius: wp("5%"),
    padding: wp("5%"),
    marginHorizontal: wp("5%"),
    marginTop: hp("2%"),
    marginBottom: hp("2%"),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  amountContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp("2%"),
    paddingBottom: hp("2%"),
    borderBottomWidth: 1,
    borderBottomColor: "rgba(66, 15, 84, 0.1)",
  },
  amountLabel: {
    fontSize: wp("4%"),
    color: "#666",
    fontFamily: "Poppins-Regular",
  },
  amount: {
    fontSize: wp("5%"),
    fontWeight: "bold",
    color: "#272D2F",
    fontFamily: "Poppins-Bold",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp("1%"),
  },
  infoLabel: {
    fontSize: wp("3.5%"),
    color: "#666",
    fontFamily: "Poppins-Regular",
  },
  infoValue: {
    fontSize: wp("3.5%"),
    color: "#272D2F",
    fontFamily: "Poppins-Medium",
  },
  statusBadge: {
    paddingHorizontal: wp("2%"),
    paddingVertical: hp("0.5%"),
    borderRadius: wp("2%"),
  },
  statusPending: {
    backgroundColor: "#FFE082",
  },
  statusCompleted: {
    backgroundColor: "#A5D6A7",
  },
  statusFailed: {
    backgroundColor: "#EF9A9A",
  },
  statusCanceled: {
    backgroundColor: "#E0E0E0",
  },
  statusText: {
    fontSize: wp("3%"),
    fontWeight: "bold",
    fontFamily: "Poppins-Medium",
  },
  formContainer: {
    backgroundColor: "#ffffff",
    borderRadius: wp("5%"),
    padding: wp("5%"),
    marginHorizontal: wp("5%"),
    marginBottom: hp("2%"),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: wp("4.5%"),
    fontWeight: "bold",
    color: "#272D2F",
    marginBottom: hp("2%"),
    fontFamily: "Poppins-Bold",
  },
  inputContainer: {
    marginBottom: hp("2%"),
  },
  inputLabel: {
    fontSize: wp("3.5%"),
    color: "#666",
    marginBottom: hp("0.5%"),
    fontFamily: "Poppins-Regular",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3E4FF",
    borderRadius: wp("3%"),
    paddingHorizontal: wp("3%"),
    height: hp("6%"),
  },
  inputIcon: {
    marginRight: wp("2%"),
  },
  input: {
    flex: 1,
    height: hp("6%"),
    fontSize: wp("4%"),
    fontFamily: "Poppins-Regular",
    color: "#272D2F",
  },
  rowInputs: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardBrandsContainer: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: hp("2%"),
  },
  cardBrandPlaceholder: {
    width: wp("15%"),
    height: hp("3%"),
    borderRadius: wp("1%"),
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: wp("1%"),
  },
  cardBrandText: {
    color: "#ffffff",
    fontSize: wp("3%"),
    fontWeight: "bold",
    fontFamily: "Poppins-Bold",
  },
  actionContainer: {
    marginHorizontal: wp("5%"),
    marginTop: hp("2%"),
  },
  payButton: {
    backgroundColor: "#420F54",
    borderRadius: wp("3%"),
    paddingVertical: hp("1.5%"),
    alignItems: "center",
    justifyContent: "center",
    marginBottom: hp("2%"),
    height: hp("6%"),
  },
  payButtonText: {
    color: "#ffffff",
    fontSize: wp("4%"),
    fontWeight: "bold",
    fontFamily: "Poppins-Bold",
  },
  cancelButton: {
    backgroundColor: "transparent",
    borderWidth: 1,
    borderColor: "#420F54",
    borderRadius: wp("3%"),
    paddingVertical: hp("1.5%"),
    alignItems: "center",
    justifyContent: "center",
    height: hp("6%"),
  },
  cancelButtonText: {
    color: "#420F54",
    fontSize: wp("4%"),
    fontWeight: "bold",
    fontFamily: "Poppins-Bold",
  },
});

export default styles;
